-- Media Server database schema (generated by: npm run db:schema)
-- Import into an existing, empty database, e.g.: mysql -u USER -p media_server < database/schema.sql

CREATE TABLE IF NOT EXISTS schema_migrations (
  version    INT UNSIGNED NOT NULL,
  name       VARCHAR(100) NOT NULL,
  applied_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Migration 1: initial schema
CREATE TABLE IF NOT EXISTS api_keys (
  id              VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  name            VARCHAR(100) NOT NULL,
  key_hash        CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SHA-256 of the API key; the key itself is never stored',
  prefix          VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  scopes          VARCHAR(64) CHARACTER SET ascii NOT NULL,
  allowed_origins TEXT CHARACTER SET ascii NOT NULL,
  quota_bytes     BIGINT UNSIGNED NOT NULL,
  used_bytes      BIGINT UNSIGNED NOT NULL DEFAULT 0,
  active          TINYINT(1) NOT NULL DEFAULT 1,
  created_at      DATETIME(3) NOT NULL,
  last_used_at    DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_api_keys_key_hash (key_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS files (
  id                CHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  key_id            VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  kind              ENUM('image', 'pdf') NOT NULL,
  mime              VARCHAR(64) CHARACTER SET ascii NOT NULL,
  ext               VARCHAR(8) CHARACTER SET ascii NOT NULL,
  size              INT UNSIGNED NOT NULL,
  width             INT UNSIGNED NULL,
  height            INT UNSIGNED NULL,
  pages             INT UNSIGNED NULL,
  original_name     VARCHAR(255) NOT NULL,
  sha256            CHAR(64) CHARACTER SET ascii NOT NULL,
  visibility        ENUM('public', 'private') NOT NULL DEFAULT 'public',
  storage           ENUM('mysql', 'disk') NOT NULL COMMENT 'Where the bytes live',
  created_at        DATETIME(3) NOT NULL,
  expires_at        DATETIME(3) NULL,
  delete_token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  PRIMARY KEY (id),
  KEY idx_files_key_created (key_id, created_at),
  KEY idx_files_expires (expires_at),
  CONSTRAINT fk_files_key FOREIGN KEY (key_id) REFERENCES api_keys (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS file_blobs (
  file_id CHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  data    LONGBLOB NOT NULL,
  PRIMARY KEY (file_id),
  CONSTRAINT fk_file_blobs_file FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS file_variants (
  file_id    CHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  name       VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'e.g. 320x320-cover-q80.webp',
  mime       VARCHAR(64) CHARACTER SET ascii NOT NULL,
  size       INT UNSIGNED NOT NULL,
  data       LONGBLOB NOT NULL,
  created_at DATETIME(3) NOT NULL,
  PRIMARY KEY (file_id, name),
  CONSTRAINT fk_file_variants_file FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO schema_migrations (version, name) VALUES (1, 'initial schema');
