import { config } from './config.js';
import { pool } from './db.js';

// IDs are case-sensitive base64url strings, so they use a binary collation: with MySQL's default
// case-insensitive collation "abc" and "ABC" would be treated as the same key.
const ID = 'CHARACTER SET ascii COLLATE ascii_bin';
const TABLE = 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';

/** Ordered, append-only list of schema changes. Never edit an applied migration; add a new one. */
export const migrations = [
  {
    version: 1,
    name: 'initial schema',
    statements: [
      `CREATE TABLE IF NOT EXISTS api_keys (
        id              VARCHAR(32) ${ID} NOT NULL,
        name            VARCHAR(100) NOT NULL,
        key_hash        CHAR(64) ${ID} NOT NULL COMMENT 'SHA-256 of the API key; the key itself is never stored',
        prefix          VARCHAR(16) ${ID} NOT NULL,
        scopes          VARCHAR(64) CHARACTER SET ascii NOT NULL,
        allowed_origins TEXT CHARACTER SET ascii NOT NULL,
        quota_bytes     BIGINT UNSIGNED NOT NULL,
        used_bytes      BIGINT UNSIGNED NOT NULL DEFAULT 0,
        active          TINYINT(1) NOT NULL DEFAULT 1,
        created_at      DATETIME(3) NOT NULL,
        last_used_at    DATETIME(3) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_api_keys_key_hash (key_hash)
      ) ${TABLE}`,

      `CREATE TABLE IF NOT EXISTS files (
        id                CHAR(16) ${ID} NOT NULL,
        key_id            VARCHAR(32) ${ID} NOT NULL,
        kind              ENUM('image', 'pdf') NOT NULL,
        mime              VARCHAR(64) CHARACTER SET ascii NOT NULL,
        ext               VARCHAR(8) CHARACTER SET ascii NOT NULL,
        size              INT UNSIGNED NOT NULL,
        width             INT UNSIGNED NULL,
        height            INT UNSIGNED NULL,
        pages             INT UNSIGNED NULL,
        original_name     VARCHAR(255) NOT NULL,
        sha256            CHAR(64) CHARACTER SET ascii NOT NULL,
        visibility        ENUM('public', 'private') NOT NULL DEFAULT 'public',
        storage           ENUM('mysql', 'disk') NOT NULL COMMENT 'Where the bytes live',
        created_at        DATETIME(3) NOT NULL,
        expires_at        DATETIME(3) NULL,
        delete_token_hash CHAR(64) ${ID} NULL,
        PRIMARY KEY (id),
        KEY idx_files_key_created (key_id, created_at),
        KEY idx_files_expires (expires_at),
        CONSTRAINT fk_files_key FOREIGN KEY (key_id) REFERENCES api_keys (id)
      ) ${TABLE}`,

      // Bytes are kept apart from metadata so listing files never reads the blobs.
      `CREATE TABLE IF NOT EXISTS file_blobs (
        file_id CHAR(16) ${ID} NOT NULL,
        data    LONGBLOB NOT NULL,
        PRIMARY KEY (file_id),
        CONSTRAINT fk_file_blobs_file FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE
      ) ${TABLE}`,

      `CREATE TABLE IF NOT EXISTS file_variants (
        file_id    CHAR(16) ${ID} NOT NULL,
        name       VARCHAR(64) ${ID} NOT NULL COMMENT 'e.g. 320x320-cover-q80.webp',
        mime       VARCHAR(64) CHARACTER SET ascii NOT NULL,
        size       INT UNSIGNED NOT NULL,
        data       LONGBLOB NOT NULL,
        created_at DATETIME(3) NOT NULL,
        PRIMARY KEY (file_id, name),
        CONSTRAINT fk_file_variants_file FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE
      ) ${TABLE}`,
    ],
  },
];

const MIGRATIONS_TABLE = `CREATE TABLE IF NOT EXISTS schema_migrations (
  version    INT UNSIGNED NOT NULL,
  name       VARCHAR(100) NOT NULL,
  applied_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (version)
) ${TABLE}`;

/** Full schema as a SQL script, for importing by hand (phpMyAdmin, mysql CLI). */
export function schemaSql() {
  const lines = [
    '-- Media Server database schema (generated by: npm run db:schema)',
    '-- Import into an existing, empty database, e.g.: mysql -u USER -p media_server < database/schema.sql',
    '',
    `${MIGRATIONS_TABLE};`,
    '',
  ];
  for (const m of migrations) {
    lines.push(`-- Migration ${m.version}: ${m.name}`);
    for (const s of m.statements) lines.push(`${s.replace(/^ {6}/gm, '')};`, '');
    lines.push(`INSERT IGNORE INTO schema_migrations (version, name) VALUES (${m.version}, '${m.name}');`, '');
  }
  return lines.join('\n');
}

/**
 * Applies pending migrations. A named lock stops two server instances starting at the same time
 * from migrating concurrently.
 */
export async function migrate() {
  const conn = await pool.getConnection();
  try {
    const [[{ locked }]] = await conn.query("SELECT GET_LOCK('media_server_migrate', 30) AS locked");
    if (locked !== 1) throw new Error('Could not acquire the migration lock');
    try {
      await conn.query(MIGRATIONS_TABLE);
      const [rows] = await conn.query('SELECT version FROM schema_migrations');
      const applied = new Set(rows.map((r) => r.version));
      const ran = [];
      for (const m of migrations) {
        if (applied.has(m.version)) continue;
        for (const statement of m.statements) await conn.query(statement);
        await conn.execute('INSERT INTO schema_migrations (version, name) VALUES (?, ?)', [m.version, m.name]);
        ran.push(m.version);
      }
      return ran;
    } finally {
      await conn.query("SELECT RELEASE_LOCK('media_server_migrate')");
    }
  } finally {
    conn.release();
  }
}

/**
 * MySQL rejects any single packet larger than max_allowed_packet, so with the MySQL storage
 * driver it must comfortably exceed the largest upload. Returns a warning string, if any.
 */
export async function checkServerSettings() {
  const [[row]] = await pool.query('SELECT @@max_allowed_packet AS packet, VERSION() AS version');
  const needed = config.maxFileSize + 2 * 1024 * 1024;
  const warning = config.storageDriver === 'mysql' && row.packet < needed
    ? `max_allowed_packet is ${Math.round(row.packet / 1048576)} MB but uploads can be ${Math.round(config.maxFileSize / 1048576)} MB. ` +
      `Set max_allowed_packet=${Math.ceil(needed / 1048576) + 4}M in my.cnf / my.ini (under [mysqld]) and restart MySQL.`
    : null;
  return { version: row.version, maxAllowedPacket: row.packet, warning };
}
